apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ngclinetcore
  labels:
    app: ngclinetcore
spec:
  replicas: {{ .Values.replicaCounts.ngclinetcore }}
  selector:
    matchLabels:
      app: ngclinetcore
  template:
    metadata:
      labels:
        app: ngclinetcore
    spec:
      containers:
      - name: "{{ .Chart.Name }}"
        image: "mbrane.azurecr.io/ishiyan/ngcli.netcore:latest"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "{{ .Values.aspnetcore.environment }}"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "16Gi"
