version: '3.2'

services:
  ngclinetcore:
    build:
      context: .
      dockerfile: Ngcli.NetCore.Dockerfile
    ports:
    - target: 80
      published: 5000
    environment:
    - ASPNETCORE_ENVIRONMENT=DockerCompose
